on:
  release:
    types: [published]

name: release

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - id: tag
      name: Get the tag
      run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - uses: azure/docker-login@v1
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASS }}'

    - name: "Build"
      uses: okteto/build@master
      env:
        COMMIT_SHA: ${{ github.sha }}
      with:
        tag: okteto/remote:${{ steps.tag.outputs.TAG }}
        buildargs: COMMIT_SHA